app_profile/urls.py
from django.conf.urls import url

from .views import put_profile, save_profile

urlpatterns = [
	url(r'^put/$', put_profile, name='put-profile'),
	url(r'^save/$', save_profile, name='save-profile')
]

app_web/urls.py
from django.conf.urls import url
import app_web.views as Views

urlpatterns = [
    url(r'^$', Views.index, name='index'),
    url(r'^dashboard/$', Views.index_dashboard, name='dashboard'),
]

leungitkeun/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^', include('app_web.urls', namespace='web')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('app_auth.urls', namespace='auth')),
    url(r'^api/riwayat/', include('app_riwayat.urls', namespace='api-riwayat')),
    url(r'^api/friend/', include('app_friend.urls', namespace='api-friend')),
    url(r'^api/profile/', include('app_profile.urls', namespace='api-profile')),
    url(r'^api/status/', include('app_status.urls', namespace='api-status')),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_profile/models.py
from django.db import models
# from django.contrib.auth.models import User
from app_auth.models import User


# Create your models here.

class Expertise(models.Model):
    """
    Description:
    Model for expertise by User

    """
    BEGINNER = 'Beginner'
    INTERMEDIATE = 'Intermediate'
    ADVANCE = 'Advance'
    EXPERT = 'Expert'
    LEGEND = 'Legend'

    LEVEL_CHOICE = (
        (BEGINNER, BEGINNER),
        (INTERMEDIATE, INTERMEDIATE),
        (ADVANCE, ADVANCE),
        (EXPERT, EXPERT),
        (LEGEND, LEGEND),
    )

    user = models.ForeignKey(to=User, related_name='expert')

    expertise = models.CharField('Expertise', max_length=45)
    level = models.CharField('Level', choices=LEVEL_CHOICE, max_length=12)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.expertise

    class Meta:
        ordering = ('expertise', 'created_at')

app_profile/views.py
from django.http import QueryDict

from app_auth import utils as auth_utils
from app_profile import utils as profile_utils
from core.abstract import views as abstractviews
from .models import Expertise


def index(request, data):
    data_user = request.session['user_login']
    data['user_riwayat'] = profile_utils.get_query_user_history(data_user['npm'])


def put_profile(request):
    def callback(user):
        PUT = QueryDict(request.body)

        if 'first_name' in PUT:
            print('hehe')
            user.first_name = PUT.get('first_name')

        if 'last_name' in PUT:
            user.last_name = PUT.get('last_name')

        if 'email' in PUT:
            user.email = PUT.get('email')

        if 'picture_url' in PUT:
            user.picture_url = PUT.get('picture_url')

        if 'id_linkedin' in PUT:
            user.id_linkedin = PUT.get('id_linkedin')

        if 'link_linkedin' in PUT:
            user.link_linkedin = PUT.get('link_linkedin')

        if 'expertise' in PUT and 'level' in PUT:

            expertise = {
                'expertise': PUT.get('expertise'),
                'level': PUT.get('level')
            }

            if 'expertise' in request.session:
                request.session['expertise'].append(expertise)
            else:
                request.session['expertise'] = [expertise]

        user.save()

        request.session['user_login'] = auth_utils.serialize_user(user)

        return request.session['user_login']

    return abstractviews.response(request, method='PUT', auth_type=abstractviews.AUTH_TYPE['LOGIN'], callback=callback)


def save_profile(request):
    def callback(user):
        result = {}
        if 'expertise' in request.session:
            lst = request.session['expertise']
            for ahli in lst:
                expert = Expertise(user=user, expertise=ahli.get('expertise'), level=ahli.get('level'))
                expert.save()

            result['expertise'] = lst

        query = QueryDict(request.body)
        if 'is_showing_score' in query:
            value = True if query.get('is_showing_score') == 'true' else False
            user.is_showing_score = value
            user.save()

        request.session['user_login'] = auth_utils.serialize_user(user)
        return request.session['user_login']

    return abstractviews.response(request, method='PUT', auth_type=abstractviews.AUTH_TYPE['LOGIN'], callback=callback)

app_profile/templates/app_profile/edit_profile.html
<div class="flex-row">
    <!--tanda seru-->
    <div class="flex-warning">
        <div class="flex-item-1"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></div>
        <!--tulisan-->
        <div class="flex-item-2"><p> Simpan perubahan Anda. </p></div>
    </div>
    <!--button href="{% url 'api-profile:save-profile' %}" -->
    <button id="save-button" type="submit" value="submit"> Simpan </button>
</div>
<div class="flex-column">
    <span id="message-success"> Berhasil tersimpan </span>
    <div id="edit-profile"> </div>
        <span class="flex-profile-content">
            <h3> NPM </h3>
            <p> {{ user_login.npm }} </p>
        </span>
        <span class="flex-profile-content">
            <h3> Data Pribadi </h3>
            <div class="center">
                <script type="in/Login"></script>
            </div>
        </span>
        <span class="flex-profile-content">
            <h3> Keahlian </h3>
            <p> - </p>
        </span>
        <form id="form-score" class="flex-profile-content">
            <h3> Tampilkan Nilai </h3>
            <label class="container">Tidak
              <input class="radio-score" type="radio" checked="checked" name="radio" value="Tidak">
                <span class="checkmark"></span>
              </label>
            <label class="container">Ya
              <input class="radio-score" type="radio" name="radio" value="Ya">
                <span class="checkmark"></span>
            </label>
        </form>
    </div>
</div>

app_profile/templates/app_profile/profile.html
{% load static %}

<div id="profile">
  <!-- if belom nyambungin ke linkedin keluar ini -->
  <!-- {% for req in request %} -->

  <!-- {% endfor %} -->
  <!--todo: silakan isi profil-->
  <div class="flex-row">
    <!--tanda seru-->

    <div class="flex-warning">
      {% if not user_login.link_linkedin %}
      <div class="flex-item-1"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></div>
      <!--tulisan-->
      <div class="flex-item-2"><p> Silakan isi profil dahulu. </p></div>
      {% endif %}
    </div>
    <!--button-->
    <div class="flex-item-3">
      <button id="tab-button-edit-profile"> Edit Profil </button>
    </div>
  </div>
  <!--todo: isi profile user-->
  <div class="flex-column">
    <!--nama-->
    <span class="flex-profile-content">
			<h3>Nama</h3>
			<p>{{ user_login.full_name }}</p>
		</span>
    <!--npm-->
    <span class="flex-profile-content">
			<h3>NPM</h3>
			<p>{{ user_login.npm }}</p>
		</span>
    <!--keahlian-->
    <span class="flex-profile-content">
			<h3>Keahlian</h3>
			<div class="keahlian">
				{% for expertise in user_login.expertise %}
				<p>{{expertise.expertise}} ({{expertise.level}}) </p>
				{% endfor %}
			</div>
		</span>
    <!--email-->
    <span class="flex-profile-content">
			<h3>Email</h3>
			<p>{{ user_login.email }}</p>
		</span>
    <!--account-->
    <span class="flex-profile-content">
			<h3>Account</h3>
			<p>{{ user_login.link_linkedin }}</p>
		</span>

  </div>
</div>

app_profile/templates/app_profile/riwayat.html
{% if user_riwayat %}
<div class="content table table-responsive">
  <table id="table-riwayat">
    <thead>
      <th> Kode </th>
      <th> Mata Kuliah </th>
      <th> SKS</th>
      <th> Nilai </th>
    </thead>
    {% for riwayat in user_riwayat %}
    <tr>
      <td> {{riwayat.kode_mk}} </td>
      <td> {{riwayat.nama_mk}} </td>
      <td> {{riwayat.jml_sks}} </td>
      <td> {{riwayat.nilai}} </td>
    </tr>
    {% endfor %}
  </table>
</div>
{% else %}
<div>
  <span> Belum ada data </span>
</div>
{% endif %}