app_auth/urls.py
from django.conf.urls import url
import app_auth.views as View
import app_auth.views as Views


urlpatterns = [
    url(r'^login/$', View.auth_login, name='login'),
    url(r'^logout/$', View.auth_logout, name='logout'),
]

app_web/urls.py
from django.conf.urls import url
import app_web.views as Views

urlpatterns = [
    url(r'^$', Views.index, name='index'),
    url(r'^dashboard/$', Views.index_dashboard, name='dashboard'),
]

leungitkeun/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^', include('app_web.urls', namespace='web')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('app_auth.urls', namespace='auth')),
    url(r'^api/riwayat/', include('app_riwayat.urls', namespace='api-riwayat')),
    url(r'^api/friend/', include('app_friend.urls', namespace='api-friend')),
    url(r'^api/profile/', include('app_profile.urls', namespace='api-profile')),
    url(r'^api/status/', include('app_status.urls', namespace='api-status')),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_web/models.py
from django.db import models

# Create your models here.

app_web/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from app_auth import forms as auth_form
from app_status import views as status_views
from app_friend import views as friend_views
from app_profile import views as profile_views
from core import strings

# Create your views here.

def index(request):
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('web:dashboard'))

    html = 'auth/login.html'
    response = {
        'TITLE': strings.TITLE,
        'page_title': 'Welcome',
        'YEAR': strings.YEAR,
        'login_form': auth_form.LoginForm,
    }

    return render(request, html, response)


def index_dashboard(request):
    if 'user_login' not in request.session:
        return HttpResponseRedirect(reverse('web:index'))

    html = 'web/index.html'
    response = {
        'TITLE': strings.TITLE,
        'page_title': 'Dashboard',
        'YEAR': strings.YEAR,
        'user_login': request.session['user_login']
    }

    status_views.index(request, response)
    friend_views.index(request, response)
    profile_views.index(request, response)

    print(request.session['user_login'])

    return render(request, html, response)

app_web/templates/web/partials/dropdownmenu.html
<!--<div id="dropdown-menu">-->
<!--&lt;!&ndash; menu using flex column &ndash;&gt;-->
<!--<div class="menu-login">-->
<!--<form id="form" method="POST" action="{% url 'web:login' %}">-->
<!--{% if messages %}-->
<!--<div class="messages-login">-->
<!--{% for message in messages %}-->
<!--<span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>-->
<!--{% endfor %}-->
<!--</div>-->
<!--{% endif %}-->
<!--{% csrf_token %}-->
<!--{{ login_form }}-->
<!--<button id="submit" type="submit" class="btn-login" value="Submit"> Sign in </button>-->
<!--</form>-->
<!--<button></button>-->
<!--</div>-->
</div>

app_web/templates/web/partials/footer.html
<p>Copyright &copy; {{ YEAR }} {{ TITLE }}</p>

app_web/templates/web/partials/header.html
<link rel="stylesheet" href="../../../static/css/base.css">{% load static %}
<nav class="header">
  <div class="navbar-base">
    <!--LOGO-->
    <div class="navbar-left">
      <div class="logo">
        <a class="logo-text" href="{% url 'web:dashboard' %}"> Leungit </a>
      </div>
    </div>
    <!--ACCOUNT-->
    <div class="navbar-right">
      <div class="account">
        <div class="menu-dropdown">
          {% if user_login %}
          <div id="btn-user">
            {% if user_login.picture_url %}
              <img src="{{ user_login.picture_url }}">
            {% else %}
              <img src="{% static 'img/boss.png' %}">
            {% endif %}
          </div>
          <div id="menu-account" class="menu-content">
            <span class="arrow-up"></span>
            <div class="square">
              <!--logged in-->
              <div id="content-about" class="content">
                <h4 class="username"> {{ user_login.username }} </h4>
                <span class="name"> {{ user_login.full_name }} </span>
              </div>
              <a class="content" href="{% url 'auth:logout' %}"> Logout </a>
            </div>
          </div>
          {% else %}
          <button id="btn-login"> Masuk </button>
          <div id="menu-login" class="menu-content">
            <span class="arrow-up"></span>
            <div class="square">
              <!--logged in-->
              <div>
                <form id="form" method="POST" action="{% url 'auth:login' %}">
                  {% if messages %}
                  <div class="messages">
                    {% for message in messages %}
                    <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                    {% endfor %}
                  </div>
                  {% endif %}
                  {% csrf_token %}
                  {{ login_form }}
                  <br>
                  <div class="center">
                    <button id="submit" type="submit" class="" value="Submit"> Masuk </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>